name: lola
on:
  push:
    branches: [ main ]
jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: nginx

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      elhay-test:
        # Docker Hub image
        image: nginx
        ports:
          - 80 
      elhay-test1:
        # Docker Hub image
        image: nginx
        ports:
          - 80 
      elhay-test2:
        # Docker Hub image
        image: nginx
        ports:
          - 80 
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: validate curl
        # Runs a script that creates a Redis client, populates
        # the client with data, and retrieves data
        run: curl elhay-test   
